let err = new Error('Error')
throw err